version: "3"

services:

  app:
    build: ./app
    restart: always
    volumes:
      - ./app/app:/app
    environment:
      NODE_ENV: "development"
      CHOKIDAR_USEPOLLING: "true"

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
