version: "3.7"

services:
  api:
    build: ./api
    restart: always
    volumes:
      - ./api/app:/app
    environment:
      NODE_ENV: "development"
      CHOKIDAR_USEPOLLING: "true"
      REFETCH_DELAY: 3600
    depends_on:
      - nginx

  app:
    build: ./app
    restart: always
    volumes:
      - ./app/app:/app
    environment:
      NODE_ENV: "development"
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - nginx

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8080:443"
    volumes:
      - ./certs:/etc/nginx/certificates
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ./logs/nginx:/var/log/nginx
