version: "3"

services:

  app:
    build:
      context: ./app
      dockerfile: prod.Dockerfile
    restart: always
    environment:
      NODE_ENV: "production"
      CHOKIDAR_USEPOLLING: "false"
    depends_on:
      - nginx

  nginx:
    build:
      context: ./nginx
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./certs:/etc/nginx/certificates
      - nginx_logs:/var/log/nginx

volumes:
  nginx_logs: