version: "3.8"

services:
  # Using NGINX to get single endpoint for app and API
  nginx:
    image: ${IMAGE_NGINX:-ghcr.io/flavienbwk/etna-rank/nginx}:${TAG:-latest}
    build:
      context: ./nginx
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - "8080:443"
    volumes:
      - ./certs:/etc/nginx/certificates
      - ./logs/nginx:/var/log/nginx
    mem_reservation: 10M
    mem_limit: 250M
    cpus: "0.5"
    depends_on:
      api:
        condition: service_healthy
      app:
        condition: service_healthy

  api:
    image: ${IMAGE_API:-ghcr.io/flavienbwk/etna-rank/api}:${TAG:-latest}
    build:
      context: ./api
      dockerfile: prod.Dockerfile
    restart: always
    volumes:
      - ./cache:/tmp/etna-rank/cache
    environment:
      REFETCH_DELAY: 3600
      INCLUDE_FDI_GRADES: "false"
    mem_reservation: 10M
    mem_limit: 250M
    cpus: "1.0"

  app:
    image: ${IMAGE_APP:-ghcr.io/flavienbwk/etna-rank/app}:${TAG:-latest}
    build:
      context: ./app
      dockerfile: prod.Dockerfile
      args:
        REACT_APP_API_ENDPOINT: "${API_ENDPOINT:-}"
        NODE_ENV: "production"
        CHOKIDAR_USEPOLLING: "false"
    restart: always
    cpus: "0.5"
    mem_reservation: 10M
    mem_limit: 100M
