version: "3"

services:
  # Using NGINX to get single endpoint for app and API
  nginx:
    image: ${IMAGE_NGINX:-ghcr.io/flavienbwk/etna-rank/nginx}:${TAG:-latest}
    build:
      context: ./nginx
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - "8080:443"
    volumes:
      - ./certs:/etc/nginx/certificates
      - ./logs/nginx:/var/log/nginx
    depends_on:
      api:
        condition: service_healthy
      app:
        condition: service_healthy

  api:
    image: ${IMAGE_API:-ghcr.io/flavienbwk/etna-rank/api}:${TAG:-latest}
    build:
      context: ./api
      dockerfile: prod.Dockerfile
    restart: always
    volumes:
      - ./cache:/tmp/etna-rank/cache
    environment:
      REFETCH_DELAY: 3600
      INCLUDE_FDI_GRADES: "false"

  app:
    image: ${IMAGE_APP:-ghcr.io/flavienbwk/etna-rank/app}:${TAG:-latest}
    build:
      context: ./app
      dockerfile: prod.Dockerfile
      args:
        REACT_APP_API_ENDPOINT: "${API_ENDPOINT:-}"
        NODE_ENV: "production"
        CHOKIDAR_USEPOLLING: "false"
    restart: always
