apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    name: ingress-nginx
  namespace: etna-rank
  name: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: etna-rank.964c196d-dee5-41e2-b8ae-a11acfbdd425.nodes.k8s.fr-par.scw.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 443
