name: Prod build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:

  build-linux:
    name: Ubuntu 20.04 prod build of etna-rank
    runs-on: ubuntu-20.04

    steps:

      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        id: extract_branch

      - name: Extract branch name on pull request
        if: github.event_name == 'pull_request'
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          ref: ${{ env.BRANCH_NAME }}

      - name: Build prod
        run: |
          docker-compose -f prod.docker-compose.yml build

      - name: Build NGINX K8S conf
        run: |
          docker build ./nginx -f ./nginx/k8s.Dockerfile -t ghcr.io/flavienbwk/etna-rank/nginx:ci-devel
